{
  "name": "nodejs-throw-new-error",
  "version": "1.0.0",
  "description": "Lançando erros",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/flaviomicheletti/nodejs-throw-new-error.git"
  },
  "author": "Flávio Micheletti",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/flaviomicheletti/nodejs-throw-new-error/issues"
  },
  "homepage": "https://github.com/flaviomicheletti/nodejs-throw-new-error#readme",
  "scripts": {
    "start": "node server.js",
    "debug": "nodemon --inspect server.js",    
    "test": "jest"
  },
  "dependencies": {
    "express": "^4.17.1"
  },
  "devDependencies": {
    "axios": "^0.19.2",
    "cors": "^2.8.5",
    "jest": "^25.1.0",
    "nock": "^13.0.0",
    "nodemon": "^2.0.4"
  }
}
